# Data Science Fundamentals Assessment

**Task 1 | Data Analyst Internship | 02-Oct-2026 to 27-Nov-2026**

This notebook introduces core Python, descriptive statistics, NumPy, Pandas, visualization, and responsible data practices. It uses a small, fictional student-performance dataset defined in the neighboring `fundamentals.py`. The data are reproducible and contain no real student information. Findings are illustrative: this constructed sample is not representative, and correlation is not causation.

Run cells from top to bottom with the project folder as the notebook kernel's working directory. Install dependencies first with `python -m pip install -r requirements.txt`.

## 2. Objectives

- Practice core Python syntax, types, control flow, functions, and collections.
- Calculate descriptive statistics from the supplied sample data.
- Use NumPy and Pandas for numeric and tabular analysis.
- Clean and validate data, create visualizations, and communicate limitations responsibly.

## 3. Introduction to Data Science

Data science uses data, computation, and domain questions to produce useful evidence. A typical lifecycle frames a question, prepares and validates data, analyzes it, communicates findings, and revises the work when needed. This assessment uses only a small fictional teaching dataset; it is not representative, and correlation does not establish causation.

In [1]:
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from fundamentals import (
    make_sample_data, validate_data, calculate_statistics, demonstrate_numpy,
    demonstrate_data_quality, create_visualizations, create_report,
)

PROJECT_DIR = Path.cwd()  # Open the notebook with the project folder as the working directory.
OUTPUT_DIR = PROJECT_DIR / "outputs"
CHART_DIR = OUTPUT_DIR / "charts"
CSV_PATH = PROJECT_DIR / "student_performance.csv"
RESULTS_PATH = OUTPUT_DIR / "results.txt"
REPORT_PATH = PROJECT_DIR / "report" / "Task_1_Data_Science_Fundamentals_Report.docx"
OUTPUT_DIR.mkdir(exist_ok=True)
CHART_DIR.mkdir(exist_ok=True)
RANDOM_SEED = 42

sample_frame = make_sample_data()  # Explicit DataFrame creation from fixed fictional records.
if not CSV_PATH.exists():
    sample_frame.to_csv(CSV_PATH, index=False)
data = pd.read_csv(CSV_PATH)
validate_data(data)
print(f"Loaded {len(data)} fictional records from {CSV_PATH.name}.")
data.head()

Loaded 20 fictional records from student_performance.csv.

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Assignments_Score,Exam_Score
0,1001,Avery,19,Female,8.0,96,82,86
1,1002,Blake,20,Male,5.5,88,74,76
2,1003,Casey,18,Female,3.0,81,68,70
3,1004,Devon,21,Male,9.0,97,90,92
4,1005,Emery,19,Female,6.5,91,78,81

## 4. Python Fundamentals

The next cell demonstrates variables, operators, conditions, loops, functions, built-in collections, a handled conversion error, and context-managed CSV file handling.

In [2]:
student_count = len(data)
study_hours = 5.8
assessment_name = "Data Science Fundamentals"
is_reproducible = True
converted_count = int("20")
arithmetic_result = 8 + 2 * 3
comparison_result = student_count >= converted_count
logical_result = is_reproducible and study_hours > 0

if study_hours >= 8:
    study_band = "high"
elif study_hours >= 4:
    study_band = "moderate"
else:
    study_band = "low"

study_totals = []
for hour_count in [2, 4, 6]:
    study_totals.append(hour_count * 2)
countdown = []
counter = 3
while counter > 0:
    countdown.append(counter)
    counter -= 1

def pass_rate(scores, pass_mark=70):
    """Return the proportion of scores meeting a pass mark."""
    if not scores:
        return 0.0
    return sum(score >= pass_mark for score in scores) / len(scores)

try:
    invalid_integer = int("not numeric")
except ValueError:
    invalid_integer = None

# Context managers close the file; remove the temporary example after reading it.
example_path = OUTPUT_DIR / "file_handling_example.csv"
try:
    with example_path.open("w", encoding="utf-8") as output_file:
        output_file.write("concept,value\nassessment,Data Science Fundamentals\n")
    with example_path.open("r", encoding="utf-8") as input_file:
        first_line = input_file.readline().strip()
finally:
    example_path.unlink(missing_ok=True)
print({"study_band": study_band, "arithmetic": arithmetic_result,
       "comparison": comparison_result, "logical": logical_result,
       "for_loop": study_totals, "while_loop": countdown,
       "pass_rate": pass_rate([68, 75, 91]), "handled_error": invalid_integer,
       "file_header": first_line})

{'study_band': 'moderate', 'arithmetic': 14, 'comparison': True, 'logical': True, 'for_loop': [4, 8, 12], 'while_loop': [3, 2, 1], 'pass_rate': 0.6666666666666666, 'handled_error': None, 'file_header': 'concept,value'}

## 5. Data Types

Python values have types that guide valid operations. The sample includes integer identifiers and ages, floating-point study hours, string names and categories, and Boolean conditions. Convert values explicitly and handle invalid input rather than silently coercing it.

In [3]:
data_type_examples = {
    "integer": (data.loc[0, "Age"], type(data.loc[0, "Age"]).__name__),
    "float": (data.loc[0, "Study_Hours"], type(data.loc[0, "Study_Hours"]).__name__),
    "string": (data.loc[0, "Name"], type(data.loc[0, "Name"]).__name__),
    "Boolean": (data.loc[0, "Attendance"] >= 90, "bool"),
}
converted_age = int("19")
print(data_type_examples)
print("Converted string to integer:", converted_age)

{'integer': (np.int64(19), 'int64'), 'float': (np.float64(8.0), 'float64'), 'string': ('Avery', 'str'), 'Boolean': (np.True_, 'bool')}
Converted string to integer: 19

## 6. Data Structures

Lists are ordered and mutable, tuples are ordered and immutable, sets store unique values, and dictionaries map keys to values. These collections make small examples readable; the analysis uses a DataFrame for the student records.

In [4]:
example_list = ["clean", "validate", "analyze"]
example_tuple = ("Age", "integer")
example_set = {"Python", "NumPy", "Python"}
example_dictionary = {"records": len(data), "dataset": "fictional student performance"}
print({"list": example_list, "tuple": example_tuple,
       "set": sorted(example_set), "dictionary": example_dictionary})

{'list': ['clean', 'validate', 'analyze'], 'tuple': ('Age', 'integer'), 'set': ['NumPy', 'Python'], 'dictionary': {'records': 20, 'dataset': 'fictional student performance'}}

## 7. Statistics

Calculate mean, median, mode, minimum, maximum, range, sample variance and standard deviation, percentiles, and Pearson correlation from the actual CSV records. Correlation describes association and does not establish cause and effect.

In [5]:
statistics, correlations = calculate_statistics(data)
display(statistics.to_frame("Exam_Score").round(2))
print("Correlation matrix:\n", correlations.round(3).to_string())
study_exam_correlation = correlations.loc["Study_Hours", "Exam_Score"]
print(f"Study-hours/exam-score Pearson correlation: {study_exam_correlation:.3f}")

                             Exam_Score
Mean                              78.10
Median                            77.50
Mode                              75.00
Minimum                           58.00
Maximum                           96.00
Range                             38.00
Variance (sample)                115.46
Standard deviation (sample)       10.75
25th percentile                   71.50
75th percentile                   86.25

Correlation matrix:
                    Study_Hours  Attendance  Assignments_Score  Exam_Score
Study_Hours              1.000       0.967              0.989       0.994
Attendance               0.967       1.000              0.969       0.973
Assignments_Score        0.989       0.969              1.000       0.998
Exam_Score               0.994       0.973              0.998       1.000
Study-hours/exam-score Pearson correlation: 0.994

## 8. NumPy

NumPy arrays support efficient numerical operations. Work with 1D exam-score data and a 2D study-hours/score array, then demonstrate indexing, slicing, elementwise arithmetic, reshaping, and mean, minimum, maximum, and sample standard deviation.

In [6]:
numpy_examples = demonstrate_numpy(data)
scores_array = numpy_examples["one_dimensional"]
study_and_score_array = numpy_examples["two_dimensional"]
example_grid = np.arange(1, 7).reshape(2, 3)
print("1D scores:", scores_array)
print("2D study/score array shape:", study_and_score_array.shape)
print("First score:", scores_array[0], "first three:", scores_array[:3])
print("Array arithmetic:\n", example_grid + 10)
print("Reshaped array:\n", example_grid)
print("Mean/min/max/sample SD:", numpy_examples["mean"], numpy_examples["minimum"],
      numpy_examples["maximum"], round(numpy_examples["standard_deviation"], 2))

1D scores: [86 76 70 92 81 64 83 72 96 75 79 68 90 74 87 58 80 62 94 75]
2D study/score array shape: (20, 2)
First score: 86 first three: [86 76 70]
Array arithmetic:
 [[11 12 13]
 [14 15 16]]
Reshaped array:
 [[1 2 3]
 [4 5 6]]
Mean/min/max/sample SD: 78.1 58 96 10.75

## 9. Pandas

Load the root CSV into a DataFrame, inspect head/tail, shape, schema, and descriptive statistics, then select, filter, sort, group, and aggregate. Check missing values and duplicate rows before cleaning.

In [7]:
data = pd.read_csv(CSV_PATH)
validate_data(data)
print("Shape:", data.shape)
print("DataFrame info:")
data.info()
display(data.head())
display(data.tail())
display(data.describe().round(2))

selected_columns = data[["Name", "Study_Hours", "Exam_Score"]]
high_attendance = data.loc[data["Attendance"] >= 90, ["Student_ID", "Name", "Attendance"]]
sorted_students = data.sort_values("Exam_Score", ascending=False)
gender_summary = data.groupby("Gender").agg(
    Student_Count=("Student_ID", "count"),
    Mean_Exam_Score=("Exam_Score", "mean"),
    Median_Exam_Score=("Exam_Score", "median"),
)
print("Selected columns:\n", selected_columns.head().to_string(index=False))
print("Rows with attendance >= 90:", len(high_attendance))
print("Top exam scores:\n", sorted_students[["Name", "Exam_Score"]].head().to_string(index=False))
display(gender_summary.round(2))
print("Missing values by column:\n", data.isna().sum().to_string())
print("Duplicate rows:", int(data.duplicated().sum()))

Shape: (20, 8)
DataFrame info:
<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Student_ID         20 non-null     int64
 1   Name               20 non-null     str
 2   Age                20 non-null     int64
 3   Gender             20 non-null     str
 4   Study_Hours        20 non-null     float64
 5   Attendance         20 non-null     int64
 6   Assignments_Score  20 non-null     int64
 7   Exam_Score         20 non-null     int64
dtypes: float64(1), int64(5), str(2)
memory usage: 1.4 KB

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Assignments_Score,Exam_Score
0,1001,Avery,19,Female,8.0,96,82,86
1,1002,Blake,20,Male,5.5,88,74,76
2,1003,Casey,18,Female,3.0,81,68,70
3,1004,Devon,21,Male,9.0,97,90,92
4,1005,Emery,19,Female,6.5,91,78,81

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Assignments_Score,Exam_Score
15,1016,Parker,22,Male,1.5,68,55,58
16,1017,Quinn,19,Female,6.0,89,77,80
17,1018,Riley,21,Male,2.0,75,59,62
18,1019,Sage,18,Female,9.5,98,92,94
19,1020,Taylor,20,Male,5.0,86,71,75

,Student_ID,Age,Study_Hours,Attendance,Assignments_Score,Exam_Score
count,20.00,20.00,20.00,20.00,20.00,20.00
mean,1010.50,19.60,5.72,87.30,75.50,78.10
std,5.92,1.31,2.53,8.63,10.87,10.75
min,1001.00,18.00,1.50,68.00,55.00,58.00
25%,1005.75,18.75,3.88,83.25,69.50,71.50
50%,1010.50,19.50,5.75,88.50,75.00,77.50
75%,1015.25,20.25,7.62,93.50,82.50,86.25
max,1020.00,22.00,10.00,99.00,94.00,96.00

Selected columns:
  Name  Study_Hours  Exam_Score
Avery          8.0          86
Blake          5.5          76
Casey          3.0          70
Devon          9.0          92
Emery          6.5          81
Rows with attendance >= 90: 9
Top exam scores:
   Name  Exam_Score
Indigo          96
  Sage          94
 Devon          92
Morgan          90
Oakley          87

            Student_Count  Mean_Exam_Score  Median_Exam_Score
Gender
Female                  9            79.22               80.0
Male                    9            75.11               75.0
Non-binary              2            86.50               86.5

Missing values by column:
 Student_ID           0
Name                 0
Age                  0
Gender               0
Study_Hours          0
Attendance           0
Assignments_Score    0
Exam_Score           0
Duplicate rows: 0

## 10. Data Cleaning

The source dataset is validated as complete. To demonstrate how decisions are made transparently, create a separate copy with one missing Attendance value and one repeated row. Detect both, remove the duplicate, impute attendance with the copy's median, and flag potential exam-score outliers using the 1.5 x IQR rule. This does not silently alter the source.

In [8]:
imperfect_data = data.copy()
imperfect_data.loc[0, "Attendance"] = np.nan
imperfect_data = pd.concat([imperfect_data, imperfect_data.iloc[[1]]], ignore_index=True)
missing_before = int(imperfect_data.isna().sum().sum())
duplicates_before = int(imperfect_data.duplicated().sum())
cleaned_data = imperfect_data.drop_duplicates().copy()
attendance_median = cleaned_data["Attendance"].median()
cleaned_data["Attendance"] = cleaned_data["Attendance"].fillna(attendance_median)
first_quartile = cleaned_data["Exam_Score"].quantile(0.25)
third_quartile = cleaned_data["Exam_Score"].quantile(0.75)
interquartile_range = third_quartile - first_quartile
lower_bound = first_quartile - 1.5 * interquartile_range
upper_bound = third_quartile + 1.5 * interquartile_range
outlier_count = int((~cleaned_data["Exam_Score"].between(lower_bound, upper_bound)).sum())
quality_results = demonstrate_data_quality(data)
print({"missing_before": missing_before, "duplicates_before": duplicates_before,
       "missing_after": int(cleaned_data.isna().sum().sum()),
       "duplicates_after": int(cleaned_data.duplicated().sum()),
       "attendance_median_used": attendance_median, "exam_score_outliers": outlier_count})
validate_data(data)

{'missing_before': 1, 'duplicates_before': 1, 'missing_after': 0, 'duplicates_after': 0, 'attendance_median_used': np.float64(88.0), 'exam_score_outliers': 0}

## 11. Visualization

Create a bar chart, line chart, histogram, scatter plot, box plot, and correlation heatmap with Matplotlib and Seaborn. Chart titles and axes identify the measures; the line connects individual records ordered by study hours and is not a time series.

In [9]:
chart_paths = create_visualizations(data, correlations)
print("Charts saved to outputs/charts:", [chart.name for chart in chart_paths])
for chart_path in chart_paths:
    image = plt.imread(chart_path)
    plt.figure(figsize=(7, 4))
    plt.imshow(image)
    plt.axis("off")
    plt.title(chart_path.stem.replace("_", " "))
    plt.show()

Charts saved to outputs/charts: ['bar_exam_score_by_gender.png', 'line_exam_score_by_study_hours.png', 'histogram_exam_scores.png', 'scatter_study_hours_exam_score.png', 'box_exam_scores_by_gender.png', 'correlation_heatmap.png']

C:\Users\rames\AppData\Local\Temp\ipykernel_1592\4059046452.py:9: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## 12. Findings

The following cell writes findings calculated from the loaded CSV. They describe this small, hand-authored fictional sample only. The high correlation is not evidence that study time causes exam scores.

In [10]:
findings = [
    f"Dataset: {len(data)} fictional records and {data.shape[1]} fields.",
    "Exam score statistics:",
    statistics.round(2).to_string(),
    "Mean exam score by gender:",
    gender_summary["Mean_Exam_Score"].round(2).to_string(),
    f"Study-hours/exam-score Pearson correlation: {study_exam_correlation:.3f}",
    f"NumPy score mean/min/max/sample standard deviation: {numpy_examples['mean']:.2f} / {numpy_examples['minimum']} / {numpy_examples['maximum']} / {numpy_examples['standard_deviation']:.2f}",
    f"Cleaning check (missing before/after): {quality_results['missing_before']}/{quality_results['missing_after']}",
    f"Cleaning check (duplicates before/after): {quality_results['duplicates_before']}/{quality_results['duplicates_after']}",
    f"Exam score outliers by 1.5 x IQR: {quality_results['exam_score_outliers']}",
    "Interpretation is descriptive; this constructed dataset cannot support population or causal conclusions.",
]
RESULTS_PATH.write_text("\n".join(findings) + "\n", encoding="utf-8")
print("\n".join(findings))

Dataset: 20 fictional records and 8 fields.
Exam score statistics:
Mean                            78.10
Median                          77.50
Mode                            75.00
Minimum                         58.00
Maximum                         96.00
Range                           38.00
Variance (sample)              115.46
Standard deviation (sample)     10.75
25th percentile                 71.50
75th percentile                 86.25
Mean exam score by gender:
Gender
Female        79.22
Male          75.11
Non-binary    86.50
Study-hours/exam-score Pearson correlation: 0.994
NumPy score mean/min/max/sample standard deviation: 78.10 / 58 / 96 / 10.75
Cleaning check (missing before/after): 1/0
Cleaning check (duplicates before/after): 1/0
Exam score outliers by 1.5 x IQR: 0
Interpretation is descriptive; this constructed dataset cannot support population or causal conclusions.

## 13. Best Practices

- Reproducibility: keep source data, package requirements, and random seeds explicit.
- Validation: check schemas, types, allowed ranges, nulls, duplicates, and potential outliers before analysis.
- Readability: use meaningful names, comments for non-obvious decisions, and documentation for reusable functions.
- Privacy: use fictional or appropriately de-identified information; do not expose student-level records.
- Visualization: label units, choose honest scales, and avoid implying a trend from unordered records.
- Interpretation: state sample size and limitations; correlation alone does not support causal conclusions.

In [11]:
validate_data(data)
create_report(data, statistics, correlations, quality_results, chart_paths)
print("Word report created:", REPORT_PATH)
print("Results saved:", RESULTS_PATH)

Word report created: c:\Users\rames\OneDrive\Desktop\Data_Analyst_Internship\Task-1-Data-Science-Fundamentals\report\Task_1_Data_Science_Fundamentals_Report.docx
Results saved: c:\Users\rames\OneDrive\Desktop\Data_Analyst_Internship\Task-1-Data-Science-Fundamentals\outputs\results.txt

## 14. Conclusion

This project demonstrates an end-to-end introductory data analysis workflow with Python, NumPy, Pandas, and clear visual communication. Re-run all notebook cells after installing the requirements to regenerate the dataset outputs. Validate every input and communicate privacy and interpretation limits before applying the workflow to real records.